services:
  # API Service
  api:
    build:
      context: .
      dockerfile: src/DndNear.API/Dockerfile
    container_name: dndnear-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - dndnear-network
    volumes:
      - ./src/DndNear.API:/app/src/DndNear.API
      - ./src/DndNear.Shared:/app/src/DndNear.Shared

  # Web Service
  web:
    build:
      context: .
      dockerfile: src/DndNear.Web/Dockerfile
    container_name: dndnear-web
    ports:
      - "5001:80"
    networks:
      - dndnear-network
    depends_on:
      - api

networks:
  dndnear-network:
    driver: bridge
